### ISSUE TITLE
exception in main method in content Demos (expected allows to run as a standalone)

### ISSUE THREAD

**Issue by homebeaver** [homebeaver/SwingSet#17]
```java
public class AutoCompleteDemo extends DefaultDemoPanel {
...

    /**
     * main method allows us to run as a standalone demo.
     */
    public static void main(String[] args) { ...
```

### BUG: main

Fast alle main Methoden funktionieren nicht in eclipse IDE:

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: Application is not launched.
	at org.jdesktop.application.Application.checkApplicationLaunched(Application.java:692)
	at org.jdesktop.application.Application.getInstance(Application.java:686)
	at org.jdesktop.swingxset.DefaultDemoPanel.injectResources(DefaultDemoPanel.java:125)
	at org.jdesktop.swingx.demos.autocomplete.AutoCompleteDemo.injectResources(AutoCompleteDemo.java:233)
	at org.jdesktop.swingxset.DefaultDemoPanel.<init>(DefaultDemoPanel.java:59)
	at org.jdesktop.swingx.demos.autocomplete.AutoCompleteDemo.<init>(AutoCompleteDemo.java:98)
	at org.jdesktop.swingx.demos.autocomplete.AutoCompleteDemo$1.run(AutoCompleteDemo.java:88)
```

**Comment by homebeaver** [comment]
In https://github.com/homebeaver/SwingSet3-demos gelöst
