### ISSUE TITLE
Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.13:deploy

### ISSUE THREAD

**Issue by homebeaver** [homebeaver/SwingSet#46]
```
[ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.13:deploy (injected-nexus-deploy) on project swingset3-demos: Remote staging failed: Failed to deploy artifacts: Could not transfer artifact io.github.homebeaver:swingset3-demos:jar:1.7.5 from/to ossrh (https://s01.oss.sonatype.org:443/service/local/staging/deployByRepositoryId/iogithubhomebeaver-1036): Access denied to https://s01.oss.sonatype.org:443/service/local/staging/deployByRepositoryId/iogithubhomebeaver-1036/io/github/homebeaver/swingset3-demos/1.7.5/swingset3-demos-1.7.5.jar. Error code 401, -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.13:deploy (injected-nexus-deploy) on project swingset3-demos: Remote staging failed: Failed to deploy artifacts: Could not transfer artifact io.github.homebeaver:swingset3-demos:jar:1.7.5 from/to ossrh (https://s01.oss.sonatype.org:443/service/local/staging/deployByRepositoryId/iogithubhomebeaver-1036): Access denied to https://s01.oss.sonatype.org:443/service/local/staging/deployByRepositoryId/iogithubhomebeaver-1036/io/github/homebeaver/swingset3-demos/1.7.5/swingset3-demos-1.7.5.jar. Error code 401, 
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: Remote staging failed: Failed to deploy artifacts: Could not transfer artifact io.github.homebeaver:swingset3-demos:jar:1.7.5 from/to ossrh (https://s01.oss.sonatype.org:443/service/local/staging/deployByRepositoryId/iogithubhomebeaver-1036): Access denied to https://s01.oss.sonatype.org:443/service/local/staging/deployByRepositoryId/iogithubhomebeaver-1036/io/github/homebeaver/swingset3-demos/1.7.5/swingset3-demos-1.7.5.jar. Error code 401, 
	at org.sonatype.nexus.maven.staging.deploy.DeployMojo.execute(DeployMojo.java:216)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	... 20 more
Caused by: org.apache.maven.artifact.deployer.ArtifactDeploymentException: Remote staging failed: Failed to deploy artifacts: Could not transfer artifact io.github.homebeaver:swingset3-demos:jar:1.7.5 from/to ossrh (https://s01.oss.sonatype.org:443/service/local/staging/deployByRepositoryId/iogithubhomebeaver-1036): Access denied to https://s01.oss.sonatype.org:443/service/local/staging/deployByRepositoryId/iogithubhomebeaver-1036/io/github/homebeaver/swingset3-demos/1.7.5/swingset3-demos-1.7.5.jar. Error code 401, 
	at org.sonatype.nexus.maven.staging.deploy.strategy.StagingDeployStrategy.finalizeDeploy(StagingDeployStrategy.java:155)
	at org.sonatype.nexus.maven.staging.deploy.DeployMojo.execute(DeployMojo.java:213)
	... 22 more
Caused by: org.apache.maven.artifact.deployer.ArtifactDeploymentException: Failed to deploy artifacts: Could not transfer artifact io.github.homebeaver:swingset3-demos:jar:1.7.5 from/to ossrh (https://s01.oss.sonatype.org:443/service/local/staging/deployByRepositoryId/iogithubhomebeaver-1036): Access denied to https://s01.oss.sonatype.org:443/service/local/staging/deployByRepositoryId/iogithubhomebeaver-1036/io/github/homebeaver/swingset3-demos/1.7.5/swingset3-demos-1.7.5.jar. Error code 401, 
	at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:146)
	at org.sonatype.nexus.maven.staging.deploy.strategy.AbstractDeployStrategy.deployUp(AbstractDeployStrategy.java:213)
	at org.sonatype.nexus.maven.staging.deploy.strategy.StagingDeployStrategy.finalizeDeploy(StagingDeployStrategy.java:125)
	... 23 more
Caused by: org.eclipse.aether.deployment.DeploymentException: Failed to deploy artifacts: Could not transfer artifact io.github.homebeaver:swingset3-demos:jar:1.7.5 from/to ossrh (https://s01.oss.sonatype.org:443/service/local/staging/deployByRepositoryId/iogithubhomebeaver-1036): Access denied to https://s01.oss.sonatype.org:443/service/local/staging/deployByRepositoryId/iogithubhomebeaver-1036/io/github/homebeaver/swingset3-demos/1.7.5/swingset3-demos-1.7.5.jar. Error code 401, 
	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:302)
	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:213)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.deploy(DefaultRepositorySystem.java:386)
	at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:142)
	... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact io.github.homebeaver:swingset3-demos:jar:1.7.5 from/to ossrh (https://s01.oss.sonatype.org:443/service/local/staging/deployByRepositoryId/iogithubhomebeaver-1036): Access denied to https://s01.oss.sonatype.org:443/service/local/staging/deployByRepositoryId/iogithubhomebeaver-1036/io/github/homebeaver/swingset3-demos/1.7.5/swingset3-demos-1.7.5.jar. Error code 401, 
	at io.takari.aether.connector.AetherRepositoryConnector$2.wrap(AetherRepositoryConnector.java:889)
	at io.takari.aether.connector.AetherRepositoryConnector$2.wrap(AetherRepositoryConnector.java:1)
	at io.takari.aether.connector.AetherRepositoryConnector$PutTask.flush(AetherRepositoryConnector.java:732)
	at io.takari.aether.connector.AetherRepositoryConnector.put(AetherRepositoryConnector.java:373)
	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:295)
	... 28 more
Caused by: io.takari.aether.connector.AuthorizationException: Access denied to https://s01.oss.sonatype.org:443/service/local/staging/deployByRepositoryId/iogithubhomebeaver-1036/io/github/homebeaver/swingset3-demos/1.7.5/swingset3-demos-1.7.5.jar. Error code 401, 
	at io.takari.aether.connector.AetherRepositoryConnector.handleResponseCode(AetherRepositoryConnector.java:397)
	at io.takari.aether.connector.AetherRepositoryConnector.access$8(AetherRepositoryConnector.java:391)
	at io.takari.aether.connector.AetherRepositoryConnector$PutTask.run(AetherRepositoryConnector.java:703)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by homebeaver** [comment]
Das Problem ist in m2e beschriebenen in


https://github.com/eclipse-m2e/m2e-core/issues/250

Siehe auch https://stackoverflow.com/questions/61536737/eclipse-maven-deploy-war-to-nexus-oss-access-denied-error-code-401-unauthorized

Dort mit workarounds.

**Comment by homebeaver** [comment]
![grafik](https://user-images.githubusercontent.com/3493126/216777240-23b522f8-108c-4949-9a72-9950f7ddd0d1.png)
